### ISSUE TITLE
The hyperbolic tanget function adds the terms instead of dividing them

### ISSUE THREAD

**Issue by MikelSalazar** [howion/activation-functions#2]
The code of the hyperbolic tanget function is:
`    return (Math.exp($x) - Math.exp(-$x)) + (Math.exp($x) + Math.exp(-$x));`

When, [in theory](https://en.wikipedia.org/wiki/Activation_function), it should be:
`    return (Math.exp($x) - Math.exp(-$x)) / (Math.exp($x) + Math.exp(-$x));`

**Comment by howion** [comment]
Fixed it with the new version and deprecated the previous one! It now just uses `Math.tanh` instead. Also added new functions including `HardTanh`. I'm sorry for the inconvenience and the late return.
